name: test
description: 'test'

runs:
  using: "composite"
  steps:
    - name: setup go
      uses: actions/setup-go@v3
      with:
        go-version: '~1.18'
    - run: |
        cd ${{ github.action_path }} && go run main.go
      shell: bash
