name: test
description: 'test'

runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: |
        echo ${{ github.action_path }}
        ${{ github.action_path }}/test.sh
      shell: bash
    - name: test
      run: |
        ls -ltr
        env
      shell: bash
