name: PR Picker
description: 'pick PR to another branch with pick PR'
inputs:
  token:
    description: 'A Github PAT'
    required: true
  prs:
    required: true
    description: "comma separated PR numbers. should be sorted the order you want to merge."
  to:
    required: true
    description: "to branch name that you want to pick PRs."
  branch_prefix:
    required: false
    description: "branch name prefix for created PR."
    default: "pick-"
  title_prefix:
    required: false
    description: "title prefix for created PR."
    default: "[pick]"
  body_tmpl:
    required: false
    description: "body template by go text/template. you can use .PRs, .Branch variable."
    default: "This PR is picking {{ .PRs }} to {{ .Branch }} branch."
  dry_run:
    type: boolean
    required: false
    description: "if true, do not execute git operation, just print commands."
    default: false

runs:
  using: "composite"
  steps:
    - name: setup go
      uses: actions/setup-go@v3
      with:
        go-version: '~1.18'
    - run: |
        git remote -v
        git fetch origin
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
    - run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        workdir=`pwd`
        cd ${{ github.action_path }} && go run main.go -prs ${{ inputs.prs}} -to ${{ inputs.to }} -branch-prefix ${{ inputs.branch_prefix }} -title-prefix ${{ inputs.title_prefix }} -body ${{ inputs.body_tmpl }} -dry-run ${{ inputs.dry_run }} -workdir $workdir

      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
