name: test
description: 'test'

runs:
  using: "composite"
  steps:
    - name: setup go
      uses: actions/setup-go@v3
      with:
        go-version: '~1.18'
    - run: test.sh
      shell: bash
    - name: test
      run: |
        ls -ltr
        env
      shell: bash
